spring:
  datasource:
    url: jdbc:mysql://localhost:3306/textile
    username: root
    password: anisanis
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

    logging:
      level:
        org.flywaydb: DEBUG
        org.hibernate.SQL: DEBUG
        jakarta.mail: DEBUG
        org.springframework.mail: DEBUG
        org.springframework: DEBUG
        org.springframework.web: DEBUG
        org.springframework.web.servlet: DEBUG
        org.springframework.web.method.annotation: DEBUG
        org.springframework.validation: TRACE
        org.springframework.http.converter.json: DEBUG
        org.hibernate: ERROR


server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: always

